kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
    - key: spray
      value: bee
      operator: Equal
      effect: NoSchedule
 

